######################################################################
# Automatically generated by qmake (3.0) ?? 11? 30 15:22:00 2015
######################################################################

TEMPLATE = app
TARGET = tcp_fir_test
INCLUDEPATH += .

# Input
HEADERS += Board.h ControlView.h login.h mainwindow.h type.h
SOURCES += Board.cpp ControlView.cpp login.cpp main.cpp mainwindow.cpp
