######################################################################
# Automatically generated by qmake (3.0) ?? 11? 28 23:16:59 2015
######################################################################

TEMPLATE = app
TARGET = tcp_fir_server
INCLUDEPATH += .

# Input
HEADERS += server.h
SOURCES += main.cpp server.cpp
